### ISSUE TITLE
cloning fails due to this file 

### ISSUE THREAD

**Issue by alexlib** [ronshnapp/MyPTV#1]
https://github.com/ronshnapp/MyPTV/blob/master/dist/git%20clone%20git%40bitbucket.org:ronshnapp-.txt

I think it's better to remove the unnecessary folders and add them to `.gitignore` so they do not disrupt the source history 

```
dist
.eggs
myptv.egg-info
```
 and in `user_manual` to remove LaTeX working files: `.bib`, `.bak`, `.out` and others. leave only `.tex`, `.bib` and figures :)

**Comment by ronshnapp** [comment]
Thanks for helping in tiding up :)
Closing the issue.
