### ISSUE TITLE
Installation (Conda directions)

### ISSUE THREAD

**Issue by leahmendelson** [ronshnapp/MyPTV#19]
OS: Windows 10
Python Version: Miniconda3 Conda 4.12.0 Python 3.9.7

The `conda` installation directions are missing a minor step after setting up the conda environment. `myptv` imports in the root folder and the tests run but `myptv` will not import in the `example` folder (to run the example workflow) unless installed after setting up the conda environment (e.g. using `pip` or `setup.py`). The directions should include this step for completeness.

**Comment by ronshnapp** [comment]
Thanks you for the comment, I added the pip installation command to the instructions.
