### ISSUE TITLE
DOC - Calibration Section

### ISSUE THREAD

**Issue by leahmendelson** [ronshnapp/MyPTV#20]
I'm going to consolidate a couple small documentation issues related to the calibration section (2.2) of the user manual here.

Acceptance blockers:
- [x] Incomplete initial guess directions (2.2.2 Initial Calibration step 2). The directions ask for initial guesses for camera position, but the new camera file is also generated with a value of _f_ = 1. _f_ does not appear to change (stays at 1) when running the calibration - this leads to high reprojection errors and calibrations that don't converge within reasonable time.

Other:
- [x] The `calibration_points_gui` workflow option is mentioned in 2.2 Calibration guide, but not in 2.1.1 The workflow.py script, which only lists 7 options for the workflow command. Please also check for other hidden workflow options and include a complete list in 2.1.1.
- [x] 2.2.2 Initial Calibration step 3 mentions choosing 6 calibration points for initial calibration - in addition to having asymmetry in point selection, the 6 points also shouldn't all be coplanar. I'd encourage you to mention this specifically in the docs. It's also a little confusing that the `example` folder has more than 6 points for each camera for this step (maybe say "at least 6 points" in the docs?)

**Comment by ronshnapp** [comment]
Thank you very much for these important comments, I fixed these issues.
