### ISSUE TITLE
example_cal folder

### ISSUE THREAD

**Issue by leahmendelson** [ronshnapp/MyPTV#22]
It's not clear what the purpose of the folder is from the user manual. Some of the data also appears to be a different format than that in the `example/calibration` folder, if this is an old calibration procedure it's likely best to remove to avoid confusing users. If it's part of a test case maybe it should move out of the main directory?

**Comment by ronshnapp** [comment]
Thanks for the comment. I made a legacy folder and moved the old examples into it to avoid this confusion.
