### ISSUE TITLE
Please add community guidelines

### ISSUE THREAD

**Issue by leahmendelson** [ronshnapp/MyPTV#23]
The "Who manages this project?" section of the Readme covers some, but not all, of the JOSS requirements ("Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support").

Please add/expand guidelines, especially for reporting issues and seeking support.

**Comment by ronshnapp** [comment]
@leahmendelson Thanks for this comment. I extended this information in the readme file and enabled the Discussions forum to facilitate discussions with the community.
