### ISSUE TITLE
JOSS paper feedback

### ISSUE THREAD

**Issue by leahmendelson** [ronshnapp/MyPTV#24]
I'll consolidate my feedback on the JOSS software paper here. Overall, I'm excited about this software and have primarily minor comments on the paper.

Major:

- [x] "State of the field" review criteria (Do the authors describe how this software compares to other commonly-used packages?): Most comparisons in the paper are to OpenPTV, which makes sense for this project, but more comparisons (e.g., ImageJ ParticleTracker, OpenLPT) could be valuable to users trying to decide what software to use 

Minor:

- [x] The "Tests" heading is slightly confusing in this context, can you make clearer you're referring to an example experiment implementation and not a summary of the software test cases?
- [x] Please directly state your working fluid (I'm assuming water, which makes that calibration error even more impressive, but this should be included in the setup details) somewhere in the experiment description

Typos:

- [x] Line 41 - extra _ (or formatting error) in one mention of MyPTV
- [x] Line 158 - incomplete reference journal title (also in user manual)

**Comment by ronshnapp** [comment]
Thank you very much for these comments!
I extended the "state of the field" to include the 2D tracking packages and the recent OpenLPT. 
I also changed the title of the "Tests" section to "Testing MyPTV in an experiment".
The experiment was indeed performed in water, and I added this information to the paper.
I also fixed the typos.
