### ISSUE TITLE
Example calibration rotation

### ISSUE THREAD

**Issue by jennifer-yin** [ronshnapp/MyPTV#37]
Hello! I'm trying to understand the rotation angles for calibration. In Figure 5, should the rotation vector for b) be (-1/4pi, -3/4pi, 0) instead of (-1/2pi, -3/4pi, 0)? Or perhaps let me know if I am misunderstanding the transformation. Thanks!

**Comment by ronshnapp** [comment]
Hi. Yes, you are correct, this is a typo. The -1/4pi angle would be more correct. I just pushed a correction for that. 
Thanks for noticing and letting me know!
