### ISSUE TITLE
Has compatibility issues with most recent version of Pillow 

### ISSUE THREAD

**Issue by 9sven6** [ronshnapp/MyPTV#45]
After a fresh install, I ran the initial_calibration command of workflow.py and tried to use +/- to zoom.
The following error appeared:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\admin_user\.pyenv\pyenv-win\versions\3.11.5\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "D:\MyPTV\Test-Project\.venv\Lib\site-packages\myptv\gui_intial_cal.py", line 792, in zoomIn
    Image.ANTIALIAS)
    ^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
```

I could get around this issue by downgrading my Pillow to 9.5.0, since in 10.0.0 some attributes were deprecated. But still, probably worth fixing, or else putting the pillow version in the install guide.

**Comment by ronshnapp** [comment]
@9sven6 Thanks for the comment. I fixed the code to use the new format (LANCZOS instead of ANTIALIAS) and added the pillow>=9.5.0 requirement. This is now on Master branch. Feel free to close this issue if you agree it is resolved.

Best,
Ron

**Comment by 9sven6** [comment]
This indeed resolved the issue. Thanks for the quick response.
