### ISSUE TITLE
Possible Issues with Local Filter

### ISSUE THREAD

**Issue by ErichZimmer** [ronshnapp/MyPTV#49]
# Preface
I noticed that one of the implemented filters (`local_filter`) appears to be a variation of the normalized Gaussian variance filter. In that filter, the first blurred image is divided by a second blurred image to remove background entities and enhance contrast. However, image A and image B are divided with the divide operator, which could cause some of the following issues
a) issue a divide by zero warning
b) cause undefined behavior for integer dtypes
c) output an all-zero array.

The following may not be likely to occur, but I have had similar situations before with the original normalized variance Gaussian filter implemented in OpenPIV-Python.

# Fix
Replace https://github.com/ronshnapp/MyPTV/blob/7b43ab62a02d1802601d2391e38bf90870cf4fad/myptv/segmentation_mod.py#L123 with something like
```python
img = np.divide( # stops image from being all black
        num, den,
        out = np.zeros_like(image),
        where = (den != 0.0)
    )   
```
which is part of OpenPIV's implementation of a similar filter ([linked here](https://github.com/OpenPIV/openpiv-python/blob/a960e182e119d3668a362df5f388458163a3608e/openpiv/preprocess.py#L335)).

# Additional Options
Do nothing as this may no longer be an issue (this was an issue about 2 years ago).

**Comment by ronshnapp** [comment]
Thanks @ErichZimmer for the comment. I changed it to per your suggestion. 

Best,
Ron
